export const stylistics = {
  colors: {
    mainBg: '#FFFFFF',
    secondBg: 'rgba(255, 255, 255, 0.4)',
    loginPageBg: '#E7EAF2',
    primaryText: '#000000',
    secondaryText: '#BDBDBD',
    secondaryGreyText: '#A6A6A6',
    secondaryLightText: '#E0E0E0',
    lightTextBtn: '#FFFFFF',
    primaryBgBtn: '#24CCA7',
    hoverBgBtn: '#2BE2BA',
    secondaryTextBtn: '#4A56E2',
    secondaryBgBtn: 'transparent',
    navIconBg: '#4A56E2',
    navIconActiveBg: '#6E78E8',
    expenseColor: '#FF6596',
    basicExpens: '#FED057',
    productsExpens: '#FFD8D0',
    carExpens: '#FD9498',
    selfCareExpens: '#C5BAFF',
    childCareExpens: '#6E78E8',
    houseExpens: '#4A56E2',
    educationExpens: '#81E1FF',
    leisureExpens: '#24CCA7',
    otherExpens: '#00AD84',
  },
  fonts: {
    body: 'Circe-Regular, sans-serif',
    bodyBold: 'Circe-Bold, sans-serif',
    heading: 'Poppins-Regular, sans-serif',
    headingBold: 'Poppins-Bold, sans-serif',
  },
  fontSizes: {
    xs: '12px',
    s: '16px',
    m: '18px',
    l: '30px',
  },
  lineHeights: {
    body: 1.5,
  },
  fontWeights: {
    normal: 400,
    bold: 700,
  },
};
